name: fastml310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterhub
  - pydot
  - graphviz
  - pytest
  - pytest-cov
  - pip
  - pip:
    - pytest-randomly
    - jupyter
    - onnx>=1.4.0
    - matplotlib
    - pandas
    - seaborn
    - pydigitalwavetools==1.1
    - pyyaml
    - tensorflow==2.14
    - torch
